import '../theme/globals.css';

import { FC, ReactNode } from 'react';
import type { Metadata } from 'next';

import { Provider } from '@/theme/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<{
  children: ReactNode;
}> = ({ children }) => (
  <html lang="en">
    <body>
      <Provider>
        <main>{children}</main>
      </Provider>
    </body>
  </html>
);

export default RootLayout;
